### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by evinw**
Had 2 "host" fields.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
Pleases sign the CLA: https://cla.strongloop.com/agreements/strongloop/loopback-example-offline-sync

**Comment by superkhau** [comment]
@evinw Do you want to sign the CLA? This has been in the backlog way too long.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
I am closing this pull request as abandoned.

**Pull request closed without merging**
