### PR TITLE
Render easy-to-read GUIDs for conflicts

### PR DESCRIPTION
**Pull request by superkhau**
- Use proquint to render easy to read GUIDs
- New IDs are based on the first 8 chars of the original guid

Connect #62

### CODE REVIEW

**Comment by superkhau** [comment]
@bajtos Code review please.

**Comment by ritch** [comment]
LGTM

**Comment by bajtos** [comment]
:+1: 

Nitpick: instead of exporting `proquint` and `Buffer`, I would personally export `getSimpleModelId` instead. That way the implementation details (proquint requires Buffer) would stay in a single place where the feature is exported.

**Comment by superkhau** [comment]
@bajtos I refactor based on your comments, see https://github.com/strongloop/loopback-example-offline-sync/pull/68

**Pull request merged**
