### PR TITLE
use middleware phases

### PR DESCRIPTION
**Pull request by hacksparrow**

### CODE REVIEW

**Comment by bajtos** [comment]
Hi @hacksparrow, thank you for the pull request. The canonical LoopBack way of configuring middleware is to use `server/middleware.json` file. Could you please rework the patch to follow that convention?

It's not possible to configure the livereload middleware this way, I am proposing to configure it in a boot script:

```js
// server/boot/livereload.js
module.exports = function(app) {
  var livereload = app.get('livereload');
  if (!livereload) return;
  
  app.middleware('initial:before', require('connect-livereload')({
    port: livereload
  }));
};
```

**Comment by hacksparrow** [comment]
@bajtos I was having issue with `loopback.static(path.dirname(app.get('indexFile')))`. Can you show a quick example of how it might be made to work with `middleware.json`? With that I will make http://docs.strongloop.com/display/public/LB/Defining+middleware way richer than how it is now.

**Comment by bajtos** [comment]
@hacksparrow oh, that's a good point. I missed that line because I was not expecting static middleware registered in the `initial:before` phase. As a rule of thumb, static middleware should go to `files` phase. By registering it in `initial:before`, your application will hit filesystem for every request, which is suboptimal.

As for using `app.get('indexFile')` in `middleware.json`, we don't support that yet :( See the first bullet point in #75 for an example of a possible implementation in loopback-boot. I am wondering if you could contribute this enhancement yourself? See https://github.com/strongloop/loopback-boot/blob/bd4c2fc968341a23e9bc997f629dcecf73f111d2/lib/compiler.js#L469-L472 and https://github.com/strongloop/loopback-boot/blob/bd4c2fc968341a23e9bc997f629dcecf73f111d2/lib/compiler.js#L561-L572 for inspiration. There is a catch though, while the paths must be handled by the compiler, the app variables should be processed by the executor. This is important for the browser scenario, where the compiler is run on the server as part of the build, while the executor is run in the browser against a client app instance.

The reason why I am concerned about the version proposed by this patch, is that this version is different from what you get scaffolded by `slc loopback` and thus it may be confusing for new LB developers. I'd like to keep this example as close to the "canonical" project layout as possible.

Thoughts?

**Comment by hacksparrow** [comment]
I agree with you about keeping this example as close to the "canonical" project layout as possible. Let me work on the implementation to make it happen.

All other points noted. Thanks.

**Comment by bajtos** [comment]
@hacksparrow ping, what's the status of this pull request?

**Comment by hacksparrow** [comment]
@bajtos PR #73 updates the example to `loopback` 2. Closing this one.

**Pull request closed without merging**
