### PR TITLE
Remove dependency on loopback-testing

### PR DESCRIPTION
**Pull request by superkhau**
- Add loopback-testing helper to server/test/helpers
- Remove loopback-testing from package.json

### CODE REVIEW

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@rmg Do you know why the port is already in use for tests running on windows? Error msg:

```
Fatal error: Port 9001 is already in use by another process.
```

http://ci.strongloop.com/job/loopback-example-offline-sync/node=0.10,os=windows/455/consoleFull#-16344998117ca194ba-b528-4e74-a19c-5de762bfc5b0

**Comment by superkhau** [comment]
Spoke with @rmg on Slack regarding this issue, not much we can do ATM due to window issues on CI. Merging since tests are fully passing on all other platforms.

**Comment by rmg** [comment]
@superkhau this is not failing only on Windows. The failures are because the tests are using a hard-coded port which prevents these tests from being run concurrently on the same system.

**Comment by rmg** [comment]
To answer the question more directly, the port is in use because https://github.com/strongloop/loopback-example-offline-sync/blob/0970290fa6d515a45f5648d49714208363ffd9a6/Gruntfile.js#L100

**Comment by rmg** [comment]
@slnode test please

**Comment by superkhau** [comment]
@rmg Thanks for the fix. Its all green now. Merging.

**Pull request merged**
